//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentDetail
    {
        public int AgentID { get; set; }
        public string AgentName { get; set; }
        public string Email { get; set; }
        public Nullable<int> AgentComission { get; set; }
        public string Website { get; set; }
        public string InvoiceTo { get; set; }
        public string Branch { get; set; }
        public string AgentDescription { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
    }
}
